version: '3'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production

  database:
    build: ./docker/database
    ports:
      - '5432:5432'
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  database:
